name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message || '', 'skip ci') }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: "7.4"
            laravel: "6.*"
            testbench: "4.*"
            unitconfig: "phpunit.xml"
            os: "ubuntu-latest"

          - php: "7.4"
            laravel: "7.*"
            testbench: "5.*"
            unitconfig: "phpunit.xml"
            os: "ubuntu-latest"

          - php: "7.4"
            laravel: "8.*"
            testbench: "6.*"
            unitconfig: "phpunit.xml"
            os: "ubuntu-latest"

          - php: "8.0"
            laravel: "8.*"
            testbench: "6.*"
            unitconfig: "phpunit.xml"
            os: "ubuntu-latest"

          - php: "8.0"
            laravel: "9.*"
            testbench: "7.*"
            unitconfig: "phpunit.xml"
            os: "ubuntu-latest"

          - php: "8.1"
            laravel: "9.*"
            testbench: "7.*"
            unitconfig: "phpunit_gt_81.xml"
            os: "ubuntu-latest"

          - php: "8.1"
            laravel: "10.*"
            testbench: "8.*"
            unitconfig: "phpunit_gt_81.xml"
            os: "ubuntu-latest"

          - php: "8.2"
            laravel: "10.*"
            testbench: "8.*"
            unitconfig: "phpunit_gt_81.xml"
            os: "ubuntu-latest"

          - php: "8.2"
            laravel: "11.*"
            testbench: "9.*"
            unitconfig: "phpunit_gt_81.xml"
            os: "ubuntu-latest"

          - php: "8.2"
            laravel: "12.*"
            testbench: "10.*"
            unitconfig: "phpunit_gt_81.xml"
            os: "ubuntu-latest"

    runs-on: ${{ matrix.os }}

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    env:
      extensions: intl, json, mbstring, dom, curl, openssl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Laravel ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-suggest --no-interaction

      - name: Run tests
        run: |
          vendor/bin/phpunit -c ${{ matrix.unitconfig }} --coverage-clover=coverage.clover
